# Generated by Django 5.2.1 on 2025-06-12 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskscheduler",
            old_name="date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="taskscheduler",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskscheduler",
            name="scheduled_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="taskscheduler",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
